package com.filipe.api.domain.venda;

import com.filipe.api.domain.caixa.Caixa;
import com.filipe.api.domain.cliente.Cliente;
import com.filipe.api.domain.fiscal.NotaFiscal;
import com.filipe.api.domain.usuario.Usuario;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "vendas")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Venda {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // Generated by BIGSERIAL in DB, so we use IDENTITY or sequence. However, UUID is the primary key.
    // numero is a BIGSERIAL UNIQUE in DB. We can use insertable = false, updatable = false.
    @Column(insertable = false, updatable = false)
    private Long numero;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "operador_id")
    private Usuario operador;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "caixa_id")
    private Caixa caixa;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cliente_id")
    private Cliente cliente;

    @Column(name = "data_hora")
    private LocalDateTime dataHora;

    @Column(name = "valor_bruto", nullable = false, precision = 15, scale = 2)
    private BigDecimal valorBruto;

    @Column(name = "valor_desconto", precision = 15, scale = 2)
    private BigDecimal valorDesconto;

    @Column(name = "valor_total", nullable = false, precision = 15, scale = 2)
    private BigDecimal valorTotal;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private StatusVenda status;

    @Column(name = "created_at", insertable = false, updatable = false)
    private LocalDateTime createdAt;

    @OneToMany(mappedBy = "venda", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<ItemVenda> itens = new ArrayList<>();

    @OneToMany(mappedBy = "venda", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Pagamento> pagamentos = new ArrayList<>();

    @OneToOne(mappedBy = "venda", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private NotaFiscal notaFiscal;

    @PrePersist
    protected void onCreate() {
        if (dataHora == null) {
            dataHora = LocalDateTime.now();
        }
    }

    public void adicionarItem(ItemVenda item) {
        itens.add(item);
        item.setVenda(this);
    }

    public void removerItem(ItemVenda item) {
        itens.remove(item);
        item.setVenda(null);
    }

    /**
     * Recalculates valorBruto, valorDesconto and valorTotal from scratch
     * by iterating over all current items.
     * Should be called after any mutation (add/remove) to keep totals consistent.
     */
    public void recalcularTotais() {
        BigDecimal bruto = BigDecimal.ZERO;
        BigDecimal desconto = BigDecimal.ZERO;

        for (ItemVenda item : itens) {
            // bruto = sum of (quantidade * precoUnitario) for every item
            bruto = bruto.add(item.getPrecoUnitario().multiply(item.getQuantidade()));
            desconto = desconto.add(item.getDesconto());
        }

        this.valorBruto = bruto;
        this.valorDesconto = desconto;
        this.valorTotal = bruto.subtract(desconto);
    }
}
